### ISSUE TITLE
 Migrate extension from Manifest V2 to Manifest V3

### ISSUE THREAD

**Issue by chinmaychahar** [chinmaychahar/SafeWeb#2]
- By June 2023, extensions that run Manifest V2 will no longer be supported on the Chrome Web Store

- [Guide](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/) to follow

- [Checklist](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/)

**Comment by HeyChobe** [comment]
Hello!

This is my first issue, i followed your instructions to make an PR and I hope it works! :)

**Comment by chinmaychahar** [comment]
Hey @HeyChobe 👋 Thanks for the PR! 
Kindly give me some time to review it and I'll get back to you.

**Comment by chinmaychahar** [comment]
Closed by #4

**Comment by chinmaychahar** [comment]
Closed by #4
