### ISSUE TITLE
setInterval functionality for timer

### ISSUE THREAD

**Issue by chinmaychahar** [chinmaychahar/SafeWeb#3]
Make the countdown timer feature working

**Comment by HeyChobe** [comment]
Hello again! I think I have a great solution for this issue, if you allow me I can try something 😄

**Comment by chinmaychahar** [comment]
Please go ahead. Make sure the timer resets to 40 sec every time the extension pop-up loads

**Comment by HeyChobe** [comment]
Sure! Can you tell more about the behavior expected?, for instance, when the countdown finish what should happens?

**Comment by chinmaychahar** [comment]
Each time background.js is executed, a new tab opens up and the timer should start from the 40:00 seconds mark. 
Ideally once the timer runs out, the tab should close but for initial functionality you could try displaying the text "Break Time Done!"  for now

**Comment by HeyChobe** [comment]
The basic behavior of the countdown is already done, you can see it in the PR, tell me if I have to change or add something 💯

**Comment by chinmaychahar** [comment]
Okay, sure

**Comment by HeyChobe** [comment]
Nice, should I use a popup to show that message?  I think we can use notifications windows that manifest v3 proposes to use once timer runs out and the tab close.

If you are agree, I can wait for the manifest to update to add it, probably later we can add animations our sounds to this.

**Comment by chinmaychahar** [comment]
I think the text div where the timer is being displayed can be simply overridden by "Break Time Done"

**Comment by HeyChobe** [comment]
> I think the text div where the timer is being displayed can be simply overridden by "Break Time Done"

Perfect

**Comment by chinmaychahar** [comment]
Should I wait for this before merging #5 @HeyChobe ?

**Comment by HeyChobe** [comment]
Yes, give me some minutes, it will be ready soon :)

**Comment by HeyChobe** [comment]
Now you can merge the changes 💯

**Comment by chinmaychahar** [comment]
Thanks @HeyChobe. Closed by #5
